# Generated by Django 4.2 on 2026-02-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree_year', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveTypes',
            fields=[
                ('elective_type_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLanguages',
            fields=[
                ('language', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='electives',
            name='degree_year',
        ),
        migrations.AlterField(
            model_name='electives',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='electives',
            name='instructor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electives',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='programs',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programs',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='electives',
            name='degree_year',
            field=models.ManyToManyField(null=True, to='catalog.degree'),
        ),
        migrations.AlterField(
            model_name='electives',
            name='elective_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.electivetypes'),
        ),
        migrations.AlterField(
            model_name='electives',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.programlanguages'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.programlanguages'),
        ),
        migrations.DeleteModel(
            name='elective_types',
        ),
    ]
