# Generated by Django 4.2 on 2026-02-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_degree_electivetypes_programlanguages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='program_id',
            new_name='program',
        ),
    ]
