# Generated by Django 4.2 on 2026-02-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_program_id_tracks_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electives',
            name='degree_year',
            field=models.ManyToManyField(blank=True, to='catalog.degree'),
        ),
    ]
