# Generated by Django 4.2 on 2026-02-24 16:41

from django.db import migrations

def add_initial_tracks(apps, schema_editor):
    Programs = apps.get_model('catalog', 'Programs')
    Tracks = apps.get_model('catalog', 'Tracks')

    cse = Programs.objects.get(name='CSE')
    dsai = Programs.objects.get(name='DSAI')

    tracks = [
        Tracks(
            name='DS',
            program=dsai
        ),
        Tracks(
            name='AI',
            program=dsai
        ),
        Tracks(
            name='RO',
            program=dsai
        ),
        Tracks(
            name='SD',
            program=cse
        ),
        Tracks(
            name='GD',
            program=cse
        ),
    ]

    Tracks.objects.bulk_create(tracks)

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_initial_programs'),
    ]

    operations = [
        migrations.RunPython(add_initial_tracks),
    ]
