# Generated by Django 4.2 on 2026-02-23 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_degree_electivetypes_programlanguages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('priorities', models.IntegerField(default=5)),
                ('degree_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.degree')),
                ('elective_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.electivetypes')),
                ('program_lang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.programlanguages')),
                ('programs', models.ManyToManyField(to='catalog.programs')),
            ],
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=6)),
                ('deadline', models.DateTimeField()),
                ('stream_id', models.ManyToManyField(to='iteration.stream')),
            ],
        ),
    ]
