# Generated by Django 4.2 on 2026-02-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iteration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteration',
            old_name='stream_id',
            new_name='streams',
        ),
        migrations.RenameField(
            model_name='stream',
            old_name='elective_type_id',
            new_name='elective_type',
        ),
    ]
